  database:
    container_name: %APP%-database
    restart: always
    image: postgres:9.5
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: %APP%
    volumes:
      - %VOLUME%/%APP%/psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
