  php:
    container_name: %APP%-php
    extends:
      file: %RELATIVE_PATH%/compose.yaml
      service: php
    build:
      context: %RELATIVE_PATH%
      target: frankenphp_dev
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./:/app/%APP%/
      - %RELATIVE_PATH%/frankenphp/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - %RELATIVE_PATH%/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      APP_NAME: %APP%
      MERCURE_EXTRA_DIRECTIVES: demo
      DATABASE_URL: postgresql://docker:docker@%APP%-database:5432/%APP%?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
